pino-debug support
lrlna/pino-colada pull request #14
Opened 2017-04-12 15:42 UTC by davidmarkclements

this adds support for pino-debug - which adds an `ns` property to each object

This is different to `name` (I think) - `ns` reflects the debug namespace, whereas `name` is being used for naming a particular log message - it's a fine distinction, but distinct nonetheless

It changes output from 
<img width="1440" alt="screen shot 2017-04-12 at 16 17 17" src="https://cloud.githubusercontent.com/assets/1190716/24966439/d7ccd9e4-1f9e-11e7-82eb-10334722bbbe.png">

to

<img width="1440" alt="screen shot 2017-04-12 at 16 37 00" src="https://cloud.githubusercontent.com/assets/1190716/24966446/dab06266-1f9e-11e7-91fe-7c022843f6cd.png">

Also works in white

<img width="1440" alt="screen shot 2017-04-12 at 16 36 45" src="https://cloud.githubusercontent.com/assets/1190716/24966456/dfb5fba4-1f9e-11e7-9fd0-b36aee0ef001.png">

cc @mcollina

2017-04-12 15:45 UTC, lrlna requested changes

2017-04-12 15:45 UTC, lrlna commented on index.js
> +    if (!obj.ns) obj.ns = ''
do you think we should just display one or the other? i.e. is there an instance where we are going to have both `obj.ns` and `obj.name` ?

2017-04-12 15:45 UTC, lrlna commented on index.js
> +    return chalk.cyan(name)
if the above comment makes sense, let's keep it to `chalk.blue`, same as in `formatName()`

2017-04-12 15:46 UTC, lrlna commented
neat neat neat!! 🍒 just had a few questions ^^

2017-04-13 11:42 UTC, davidmarkclements commented
So, `name` is a pino option, whereas `ns` is unique to pino-debug and corresponds to the debug name rather than the pino name. (Use of ns in pino-debug predates the name optin). It's unlikely that these two would ever be in the same log message, but still possible.

We could treat them as the same, but we would have to combine them in some way if they're both present.

My take is, that there's a usefulness tp having both a name, and a namespace - for instance module (say merry) could set ns to 'merry' while a http operatins would remain with name of 'http'

I'll defer to your preference either way and update PR if needed

2017-04-20 09:10 UTC, lrlna commented
@davidmarkclements ahhh, cool! I haven't worked with `pino-debug` directly yet; totally makes sense to keep both then.

2017-04-20 09:10 UTC, merged

2017-04-20 09:11 UTC, lrlna commented
📦 `1.4.0` 📦